language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-marman' ]; then cd .. && eval "mv $currentfolder generator-marman" && cd generator-marman; fi

