language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-marionette-base-spa' ]; then cd .. && eval "mv $currentfolder generator-marionette-base-spa" && cd generator-marionette-base-spa; fi

